### ISSUE TITLE
How to clean mongo db ?

### ISSUE THREAD

**Issue by pseudom** [castorjs/castor-core#13]
The documentation for cleaning the database is deep in doc (and not easely to find)

**Comment by parmentf** [comment]
First, let's answer the question.

Use [castor-clean](https://github.com/castorjs/castor-clean) to remove the main collection (and all its associated collections) from MongoDB.

```bash
$ npm install castor-clean -g
$ ls
repository
repository.json
$ grep collectionName repository.json
  "collectionName" : "data",
$ castor-clean data
```

Second: let's add the information to the documentation.
