### ISSUE TITLE
Bad URL displayed: configuration files mess

### ISSUE THREAD

**Issue by parmentf** [castorjs/castor-core#16]
I used `castor-core`'s app, called [`lodex`](https://github.com/Inist-CNRS/lodex), and gave an -implicit- configuration file, by creating a `/datas/lodex/config.json` file, alongside to the empty `/datas/lodex/config` directory.

The  `config.json` file contains only:
```json
{
    "port": "8080"
}
```

And when I run the castor-core, using `./lodex /datas/lodex/config`, the output is:
```
Load configuration file. /datas/lodex/config.json
Set view directory.  /home/parmentf/dev/lodex
Watching hot directory.  /datas/lodex/config
Server is listening. http://127.0.0.1:3000/
Files and Database are synchronised.
Corpus fields computed.
```
which is controversial: the said configuration file taken into account is the right one (`/datas/lodex/config.json`), but port the server says it is listening to (`3000`) is not the one set in the configuration file (`8080`).

**However** the working URL use the right port: 8080!

**Comment by parmentf** [comment]
At [line 121 of starter.js](https://github.com/castorjs/castor-core/blob/master/starter.js#L121), the `port` in `config` is 3000, and `baseURL` is `undefined`, that's why `baseURL` is then set to `http://127.0.0.1:3000`.

Once the warmup has been called, the config object does not contain any reference to the 8080 port.
In [index.js of castor-core, line 26](https://github.com/castorjs/castor-core/blob/master/app/index.js#L26), here is the content of `config`:

```javascript
{
  config: 
   { connectionURI: 'mongodb://localhost:27017/lodex/',
     connexionURI: 'mongodb://localhost:27017/lodex/',
     collectionsIndexName: 'px_index',
     collectionName: 'hotfolder',
     debug: false,
     trustProxy: false,
     port: '3000',
     logFormat: 'combined',
     title: 'Change title',
     description: 'Change description',
     itemsPerPage: 30,
     concurrency: 4,
     writeConcern: 1,
     rootURL: undefined,
     delay: 250,
     prefixURL: '',
     prefixKEY: 'ark:/XXX',
     maxFileSize: 10485760,
     acceptFileTypes: [],
     heartrate: 5000,
     filesToIgnore: 
      [ '**/.*',
        '~*',
        '*~',
        '*.sw?',
        '*.old',
        '*.bak',
        '**/node_modules',
        'Thumbs.db' ],
     tempPath: '/tmp',
     dataPath: '/datas/lodex/config',
     viewPath: '/home/ADS.INTRA.INIST.FR/parmentf/dev/castor-core/app/views',
     middlewares: [],
     models: {},
     markdown: undefined,
     filters: [],
     routes: {},
     loaders: {},
     resources: {},
     operators: {},
     browserifyModules: [],
     corpusFields: {},
     documentFields: {},
     _: [ '/datas/lodex/config' ],
     help: false,
     h: false,
     version: false,
     V: false,
     verbose: false,
     v: false,
     d: false,
     theme: '/home/ADS.INTRA.INIST.FR/parmentf/dev/lodex',
     baseURL: 'http://127.0.0.1:3000',
     Errors: 
      { PropertyNotFound: [Function: NewError],
        CollectionNotFound: [Function: NewError],
        IndexNotFound: [Function: NewError],
        PageNotFound: [Function: NewError],
        TableNotFound: [Function: NewError],
        InvalidParameters: [Function: NewError],
        Forbidden: [Function: NewError],
        BadConfig: [Function: NewError] } } }
```

But once at [line 515](https://github.com/castorjs/castor-core/blob/fcde3eb7ae5bdc2f4978c615107662f309392774/app/index.js#L515), the `port` value is `8080`!

**Comment by touv** [comment]
fixed in https://github.com/castorjs/castor-core/commit/c4720b036b56cd3f93bac6cabd9f4d8a97f25082
