### ISSUE TITLE
Handling SIGINT and SIGTERM system messages

### ISSUE THREAD

**Issue by kerphi** [castorjs/castor-core#19]
When using castor-core in docker, SIGTERM or SIGINT system message will be sent to nodejs process when docker want the process to be stopped.

I think this code could help to cleanup the application and quit faster (without that, docker wait few seconds before killing hard the process)
I don't know exactly where this code should be put (in starter.js ?) and maybe it should also take care of closing mongodb connections and/or http server connections before process.exit(1). 

```javascript
// exit on CTRL+C
exitOnSignal('SIGINT');
exitOnSignal('SIGTERM');
function exitOnSignal(signal) {
  process.on(signal, function() {
    console.log('Caught ' + signal + ', exiting');
    process.exit(1);
  });
}
```

**Comment by kerphi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qJVF8rBI&#x2F;14-permettre-de-stopper-l-application-avec-un-ctrl-c"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Permettre de stopper l&#39;application avec un CTRL+C</a>

**Comment by parmentf** [comment]
I don't think `exitOnSignal()` is a nodejs function.
But one could use [`process.on('SIGINT')`](https://nodejs.org/docs/latest-v4.x/api/process.html#process_signal_events)

**Comment by nojhamster** [comment]
@parmentf 
> function exitOnSignal(signal) {
   process.on(signal, ...)
   }

**Comment by parmentf** [comment]
:+1: I need to learn to read. Or to sleep more ;)
